### ISSUE TITLE
PA review- User auth

### ISSUE THREAD

**Issue by astrauli** [Strauaar/TixFix#1]

**Comment by evhumphrey** [comment]
Looks good! A few things:

- [x] Change placeholder and input text styling on inputs (in your session modal) to be a sans-serif font, which the rest of your site uses
- [x] Is OAuth going to be a feature? Change the Facebook button to a "Demo" button for now.
- [x] Style error messages 
- [x] Remove "Forgot Password". You could implement this as a bonus; but you don't want to have features that don't work on your site (a recruiter may click on this and wonder why it doesn't work)
- [x] When creating a new account or logging in, your modal should close after successful submission
- [x] Remove extraneous things in dropdown (Friends, Gift codes, etc). You don't want to have things that seem like features but aren't actually implemented (because a recruiter will expect anything they can interact with should work). 

Let me know if you have any questions about this! (You can Slack me)
